#! /bin/sh


nvidia-settings --load-config-only &
killall sxhkd &
sxhkd &
killall dunst &
dunst &
lxsession &
nitrogen --restore &
setxkbmap -layout se -variant nodeadkeys &
picom --experimental-backends --backend glx &
killall flameshot &
flameshot &
killall mullvad-gui &
mullvad-vpn &
~/.config/bspwm/polybar.sh &
xsetroot -cursor_name left_ptr &
wmname LG3D &
bsp-layout set tall &



python3 ~/.config/bspwm/config.py
